export const datas = [
  {
    id: 1,
    title: "Motor Yacht",
    slug: "motor-yacht",
    desc: "Speed and luxury combined for fast, stylish escapes on the open sea",
    guest: 12,
    cabins: 6,
    knots: 30,
    price: 2500,
    image: "/assets/home/explor/Container.jpg",
  },
  {
    id: 2,
    title: "Sailing Yacht",
    slug: "sailing-yacht",
    desc: "Embrace the calm of classic sailing on a wind-powered journey",
    guest: 8,
    cabins: 4,
    knots: 12,
    price: 1800,
    image: "/assets/home/explor/Container-1.jpg",
  },
  {
    id: 3,
    title: "Catamaran",
    slug: "catamaran",
    desc: "Spacious and stable, ideal for family trips and group adventures",
    guest: 8,
    cabins: 4,
    knots: 12,
    price: 5500,
    image: "/assets/home/explor/Container-2.jpg",
  },
  {
    id: 4,
    title: "Motor Yacht",
    slug: "motor-yacht",
    desc: "Speed and luxury combined for fast, stylish escapes on the open sea",
    guest: 12,
    cabins: 6,
    knots: 30,
    price: 2500,
    image: "/assets/home/explor/Container-3.jpg",
  },
  {
    id: 5,
    title: "Sailing Yacht",
    slug: "sailing-yacht",
    desc: "Embrace the calm of classic sailing on a wind-powered journey",
    guest: 8,
    cabins: 4,
    knots: 12,
    price: 1800,
    image: "/assets/home/explor/Container-4.jpg",
  },
  {
    id: 6,
    title: "Catamaran",
    slug: "catamaran",
    desc: "Spacious and stable, ideal for family trips and group adventures",
    guest: 8,
    cabins: 4,
    knots: 12,
    price: 5500,
    image: "/assets/home/explor/Container-5.jpg",
  },
];

export const topDestination = [
  {
    id: 1,
    title: "Miami ​Florida",
    price: 1500,
    image: "/assets/home/top/Frame1.jpg",
  },
  {
    id: 2,
    title: "Miami ​Florida",
    price: 1500,
    image: "/assets/home/top/Frame2.jpg",
  },
  {
    id: 3,
    title: "Miami ​Florida",
    price: 1500,
    image: "/assets/home/top/Group3.jpg",
  },
  {
    id: 4,
    title: "Miami ​Florida",
    price: 1500,
    image: "/assets/home/top/Group4.jpg",
  },
];

export const edatas = [
  {
    id: 1,
    title: "Motor Yacht",
    desc: "Speed and luxury combined for fast, stylish escapes on the open sea",
    guest: 12,
    cabins: 6,
    knots: 30,
    price: 2500,
    image: "/assets/home/explor/Container.jpg",
  },
  {
    id: 2,
    title: "Sailing Yacht",
    desc: "Embrace the calm of classic sailing on a wind-powered journey",
    guest: 8,
    cabins: 4,
    knots: 12,
    price: 1800,
    image: "/assets/home/explor/Container-1.jpg",
  },
  {
    id: 3,
    title: "Catamaran",
    desc: "Spacious and stable, ideal for family trips and group adventures",
    guest: 8,
    cabins: 4,
    knots: 12,
    price: 5500,
    image: "/assets/home/explor/Container-2.jpg",
  },
];
